name: Cognito React Starter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check Format
        run: npx prettier --check .

      - name: Audit dependencies
        run: |
          set +e
          npm audit --json
          set -e

      - name: Build
        run: npm run build

      - name: Start HTTP server
        run: npm install -g serve

      - name: Run application
        run: serve -s build &

      - name: Check if app is running
        run: curl -sSf http://localhost:3000 || exit 1
